<?php

namespace Database\Seeders;

use App\Models\Speciality;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class SpecialitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $specialities = [
            'Autres',
            'Electricité',
            'Industrie',
            'Dépollution',
            'Génie civil',
            'CFO CFA',
            'chaudronnerie',
            'électromécanique',
            'éolien',
            'industrialisation',
            'industriel',
            'mécanique',
            'MOEX',
            'nucléaire',
            'oil',
            'senior',
            'structure',
            'maintenance',
            'montage-mise en service',
            'production',
            'Business manager',
            'Ingénieur d\'affaires',
            'Ingénieur commercial',
            'Commercial TP',
            'Technico-commercial',
            'Assistante ADV',
            'Chargé d\'affaires',
            'études',
            'travaux éolien',
            'coordinateur chantier',
            'batiment',
            'BTP',
            'électricité',
            'Electricité',
            'Mécanique',
            'Technique',
            'Business Unit',
            'de site',
            'Grands Comptes TP',
            'infrastructure',
            'maintenance',
            'projet MOEX',
            'travaux',
            'programme immobiliers',
            'Méthode',
            'Recherche',
            'Etudes',
            'Sécurité',
            'process énergie',
            'amélioration continue',
            'calcul',
            'conception mécanique',
            'Projets',
            'génie chimique',
            'Mécanique',
            'Formateur testeur',
            'Formateur CACES',
            'Formateur technique',
            'électricité',
            'électrotechnique',
            'mécanique',
            'Projeteur TCE',
            'agence',
            'produit four verre',
            'agence et matériel',
            'atelier',
            'automatisme',
            'BE',
            'BE civil',
            'business line',
            'commercial fluid management',
            'commercial fluide',
            'commercial maintenance',
            'commercial régional',
            'contrat commerciaux',
            'd\'affaire',
            'd\'agence',
            'd\'agence BTP',
            'd\'atelier',
            'd\'usine',
            'de site',
            'EIA',
            'études',
            'exploitation',
            'grand compte financier',
            'Maitrise ouvrage',
            'méthode maintenance',
            'logistique industrielle',
            'opérationnel',
            'poduit four verre',
            'produit four verrier',
            'R&D',
            'régional',
            'SAV',
            'SAV industrie',
            'technique',
            'technique de zone',
            'technique régional',
            'travaux maintenance',
            'travaux neuf et maintenance industrie',
            'déploiement Fibre optique',
            'methode industiralisation',
            'chantier éolien',
            'de production',
            'mise en service',
            'mise en service automatisme',
            'mise en service EIA',
            'de maintenance',
            'Agent de fabrication',
            'Ajusteur outilleur conventionnel',
            'ATC',
            'automaticien',
            'automatisme',
            'Cableur filaire',
            'Cadre automaticien',
            'Chaudronnier soudeur',
            'CN',
            'CN P3',
            'CND',
            'Conducteur',
            'Conduite utilités',
            'Conventionnel',
            'Cordiste, maintenance nucléaire',
            'décolleteur cn',
            'Electromécanicien',
            'Electromécanicien CN',
            'Électrotechnicien',
            'Electrotechnicien de maintance',
            'Eletromécanicien',
            'Eletromécanicien itinérant',
            'éolien',
            'éolien',
            'exploitation',
            'filaire',
            'Fraiseur',
            'Fraiseur CN',
            'Fraiseur tourneur CN',
            'HSE',
            'industrialisation ligne de production',
            'industrialisation usinage',
            'industrie',
            'machine outil',
            'méthode',
            'méthode industrialisation',
            'méthode maintenance',
            'méthode production',
            'méthode usinage',
            'polyvalent',
            'projet électricité',
            'régleur',
            'Tourneur-fraiseur',
            'CVC',
            'Mécanicien'
        ];
        
        foreach ($specialities as $speciality) {
            Speciality::create(['name' => $speciality]);
        }

    }
}
